#!/usr/bin/env bash

ARDUINO_BUILD_DIR=$(ls -d /tmp/arduino_build_*)
TIMESTAMP=`date +%F-%H_%M_%S`

echo "Please enter a version tag (for example v1_0_3): "
read VERSION_TAG
PACKAGE="stand_alone_cdem_firmware_${VERSION_TAG}"

echo "Copying all the required files to a package dir ${PACKAGE}"

mkdir "${PACKAGE}"

# Copy all the required tools and boot-loader images
cp ~/.arduino15/packages/esp32/tools/esptool_py/2.6.1/esptool.py "./${PACKAGE}"
cp ~/.arduino15/packages/esp32/hardware/esp32/1.0.4/tools/partitions/boot_app0.bin "./${PACKAGE}"
cp ~/.arduino15/packages/esp32/hardware/esp32/1.0.4/tools/sdk/bin/bootloader_dio_80m.bin "./${PACKAGE}"

# Copy the firmware binaries
cp "${ARDUINO_BUILD_DIR}/SmartMeter_FeatherFirmware.ino.bin" "./${PACKAGE}"
cp "${ARDUINO_BUILD_DIR}/SmartMeter_FeatherFirmware.ino.partitions.bin" "./${PACKAGE}"

echo "Generating package tar gz ready for upload"
tar -cpzf "${PACKAGE}.tar.gz" "./${PACKAGE}"
