#!/usr/bin/env bash

DEVICE="/dev/ttyUSB0"
OUTDIR="./release"

PACKAGE=$(ls stand_alone_cdem_firmware_*.tar.gz)
echo "Found package ${PACKAGE}"

tar -xvf "${PACKAGE}"

PACKAGEDIR="${PACKAGE%.tar.gz}"
cd "${PACKAGEDIR}"

python esptool.py --chip esp32 --port "${DEVICE}" --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0xe000 ./boot_app0.bin 0x1000 ./bootloader_dio_80m.bin 0x10000 ./SmartMeter_FeatherFirmware.ino.bin 0x8000 ./SmartMeter_FeatherFirmware.ino.partitions.bin